var images = {
    img_00_arrow_left: imagesPath + theme + "00_arrow_left.png",
    img_00_arrow_right: imagesPath + theme + "00_arrow_right.png",
    img_00_badge_bg: imagesPath + "00_badge_bg.sci",
    img_00_badge_bg_ef: imagesPath + theme + "00_badge_bg_ef.sci",
    img_00_button_01: imagesPath + "00_button_01.sci",
    img_00_button_01_ef: imagesPath + theme + "00_button_01_ef.sci",
    img_00_button_01_ef_dim: imagesPath + theme + "00_button_01_ef_dim.sci",
    img_00_button_01_ef_press: imagesPath + theme + "00_button_01_ef_press.sci",
    img_00_button_01_focus: imagesPath + "00_button_01_focus.sci",
    img_00_button_02: imagesPath + "00_button_02.sci",
    img_00_button_02_ef: imagesPath + "00_button_02_ef.sci",
    img_00_button_02_ef_press: imagesPath + "00_button_02_ef_press.sci",
    img_00_button_03: imagesPath + "00_button_03.sci",
    img_00_button_expand_closed: imagesPath + "00_button_expand_closed.png",
    img_00_button_expand_closed_ef: imagesPath + theme + "00_button_expand_closed_ef.png",
    img_00_button_expand_opened: imagesPath + "00_button_expand_opened.png",
    img_00_button_expand_opened_ef: imagesPath + theme + "00_button_expand_opened_ef.png",
    img_00_button_left: imagesPath + "00_button_left.png",
    img_00_button_left_ef: imagesPath + theme + "00_button_left_ef.png",
    img_00_button_off: imagesPath + theme + "00_button_off.png",
    img_00_button_off_dim: imagesPath + theme + "00_button_off_dim.png",
    img_00_button_on: imagesPath + theme + "00_button_on.png",
    img_00_button_on_dim: imagesPath + theme + "00_button_on_dim.png",
    img_00_button_on_off_handler: imagesPath + theme + "00_button_on_off_handler.png",
    img_00_button_on_off_handler_dim: imagesPath + theme + "00_button_on_off_handler_dim.png",
    img_00_button_on_off_handler_focus: imagesPath + theme + "00_button_on_off_handler_focus.png",
    img_00_button_plus: imagesPath + "00_button_plus.png",
    img_00_button_plus_ef: imagesPath + "00_button_plus_ef.png",
    img_00_button_radio: imagesPath + "00_button_radio.png",
    img_00_button_radio_Activated: imagesPath + theme + "00_button_radio_Activated.png",
    img_00_button_radio_Activated_dim: imagesPath + theme + "00_button_radio_Activated_dim.png",
    img_00_button_radio_bg: imagesPath + theme + "00_button_radio_bg.png",
    img_00_button_radio_bg_dim: imagesPath + theme + "00_button_radio_bg_dim.png",
    img_00_button_radio_dim: imagesPath + "00_button_radio_dim.png",
    img_00_button_radio_dim_bg: imagesPath + "00_button_radio_dim_bg.png",
    img_00_button_radio_Disabled: imagesPath + "00_button_radio_Disabled.png",
    img_00_button_radio_focus: imagesPath + theme + "00_button_radio_focus.png",
    img_00_button_radio_normal1: imagesPath + theme + "00_button_radio_normal1.png",
    img_00_button_radio_normal2: imagesPath + theme + "00_button_radio_normal2.png",
    img_00_button_radio_press: imagesPath + theme + "00_button_radio_press.png",
    img_00_button_radio_press1: imagesPath + "00_button_radio_press1.png",
    img_00_button_radio_press2: imagesPath + "00_button_radio_press2.png",
    img_00_button_radio_press_bg: imagesPath + theme + "00_button_radio_press_bg.png",
    img_00_button_radio_select: imagesPath + "00_button_radio_select.png",
    img_00_button_radio_select_dim: imagesPath + "00_button_radio_select_dim.png",
    img_00_button_reveal: imagesPath + "00_button_reveal.png",
    img_00_button_right: imagesPath + "00_button_right.png",
    img_00_button_right_ef: imagesPath + theme + "00_button_right_ef.png",
    img_00_category_button: imagesPath + theme + "00_category_button.sci",
    img_00_category_button_focus: imagesPath + theme + "00_category_button_focus.sci",
    img_00_category_left_gradation: imagesPath + theme + "00_category_left_gradation.png",
    img_00_category_panel_bg: imagesPath + theme + "00_category_panel_bg.sci",
    img_00_category_panel_bg_ef: imagesPath + theme + "00_category_panel_bg_ef.sci",
    img_00_category_right_gradation: imagesPath + theme + "00_category_right_gradation.png",
    img_00_check_Activated: imagesPath + theme + "00_check_Activated.png",
    img_00_check_Activated_dim: imagesPath + theme + "00_check_Activated_dim.png",
    img_00_check_bg: imagesPath + theme + "00_check_bg.png",
    img_00_check_bg_dim: imagesPath + "00_check_bg_dim.png",
    img_00_check_bg_press: imagesPath + "00_check_bg_press.png",
    img_00_check_checking: imagesPath + "00_check_checking.png",
    img_00_check_checking_dim: imagesPath + "00_check_checking_dim.png",
    img_00_check_dim: imagesPath + theme + "00_check_dim.png",
    img_00_check_dim_bg: imagesPath + theme + "00_check_dim_bg.png",
    img_00_check_Disabled: imagesPath + "00_check_Disabled.png",
    img_00_check_focus: imagesPath + theme + "00_check_focus.png",
    img_00_check_press: imagesPath + theme + "00_check_press.png",
    img_00_check_press_bg: imagesPath + theme + "00_check_press_bg.png",
    img_00_circle_bg: imagesPath + theme + "00_circle_bg.png",
    img_00_circle_bg_ef: imagesPath + theme + "00_circle_bg_ef.png",
    img_00_circle_bg_ef_dim: imagesPath + theme + "00_circle_bg_ef_dim.png",
    img_00_circle_bg_ef_press: imagesPath + theme + "00_circle_bg_ef_press.png",
    img_00_circle_button_focus: imagesPath + theme + "00_circle_button_focus.png",
    img_00_color_picker_brightness: imagesPath + "00_color_picker_brightness.png",
    img_00_color_picker_brightness_h: imagesPath + "00_color_picker_brightness_h.png",
    img_00_color_picker_color: imagesPath + "00_color_picker_color.png",
    img_00_color_picker_color_h: imagesPath + "00_color_picker_color_h.png",
    img_00_color_picker_custom_color: imagesPath + "00_color_picker_custom_color.png",
    img_00_color_picker_custom_color_h: imagesPath + "00_color_picker_custom_color_h.png",
    img_00_color_picker_handler: imagesPath + "00_color_picker_handler.png",
    img_00_color_picker_handler_focus: imagesPath + "00_color_picker_handler_focus.png",
    img_00_color_picker_saturation: imagesPath + "00_color_picker_saturation.png",
    img_00_color_picker_saturation_h: imagesPath + "00_color_picker_saturation_h.png",
    img_00_contacts_button_bg: imagesPath + "00_contacts_button_bg.sci",
    img_00_contacts_button_bg_ef: imagesPath + theme + "00_contacts_button_bg_ef.sci",
    img_00_contacts_button_bg_press_ef: imagesPath + theme + "00_contacts_button_bg_press_ef.sci",
    img_00_date_picker_dot: imagesPath + "00_date_picker_dot.png",
    img_00_edit_field_clear: imagesPath + "00_edit_field_clear.png",
    img_00_edit_field_line_round_bg_01: imagesPath + "00_edit_field_line_round_bg_01.sci",
    img_00_edit_field_no_line_square_bg: imagesPath + "00_edit_field_no_line_square_bg.sci",
    img_00_edit_field_round_bg: imagesPath + "00_edit_field_round_bg.sci",
    img_00_effect_tab_bounce_left: imagesPath + theme + "00_effect_tab_bounce_left.png",
    img_00_effect_tab_bounce_left_h: imagesPath + "00_effect_tab_bounce_left_h.png",
    img_00_effect_tab_bounce_right: imagesPath + theme + "00_effect_tab_bounce_right.png",
    img_00_effect_tab_bounce_right_h: imagesPath + "00_effect_tab_bounce_right_h.png",
    img_00_effect_title_tab_bounce_left: imagesPath + "00_effect_title_tab_bounce_left.png",
    img_00_effect_title_tab_bounce_right: imagesPath + "00_effect_title_tab_bounce_right.png",
    img_00_effect_toolbar_tab_bounce_left: imagesPath + "00_effect_toolbar_tab_bounce_left.png",
    img_00_effect_toolbar_tab_bounce_left_h: imagesPath + "00_effect_toolbar_tab_bounce_left_h.png",
    img_00_effect_toolbar_tab_bounce_right: imagesPath + "00_effect_toolbar_tab_bounce_right.png",
    img_00_effect_toolbar_tab_bounce_right_h: imagesPath + "00_effect_toolbar_tab_bounce_right_h.png",
    img_00_fast_scroll_handler: imagesPath + "00_fast_scroll_handler.sci",
    img_00_fast_scroll_handler_h: imagesPath + "00_fast_scroll_handler_h.sci",
    img_00_fast_scroll_popup_bg: imagesPath + "00_fast_scroll_popup_bg.sci",
    img_00_fast_scroll_popup_bg_ef: imagesPath + "00_fast_scroll_popup_bg_ef.sci",
    img_00_fast_scroll_rollover_bg: imagesPath + "00_fast_scroll_rollover_bg.sci",
    img_00_fast_scroll_rollover_bg_focus: imagesPath + "00_fast_scroll_rollover_bg_focus.sci",
    img_00_fast_scroll_rollover_bg_line_focus: imagesPath + theme + "00_fast_scroll_rollover_bg_line_focus.sci",
    img_00_focus: imagesPath + theme + "00_focus.sci",
    img_00_grid_select_check: imagesPath + "00_grid_select_check.png",
    img_00_grid_select_check_bg: imagesPath + "00_grid_select_check_bg.png",
    img_00_grid_select_check_bg_press: imagesPath + "00_grid_select_check_bg_press.png",
    img_00_groupedlist_bg_focus: imagesPath + "00_groupedlist_bg_focus.sci",
    img_00_groupedlist_bg_press: imagesPath + "00_groupedlist_bg_press.sci",
    img_00_groupedlist_bottom_bg_focus: imagesPath + "00_groupedlist_bottom_bg_focus.sci",
    img_00_groupedlist_bottom_bg_press: imagesPath + "00_groupedlist_bottom_bg_press.sci",
    img_00_groupedlist_center_bg_focus: imagesPath + "00_groupedlist_center_bg_focus.sci",
    img_00_groupedlist_center_bg_press: imagesPath + "00_groupedlist_center_bg_press.sci",
    img_00_groupedlist_top_bg_focus: imagesPath + "00_groupedlist_top_bg_focus.sci",
    img_00_groupedlist_top_bg_press: imagesPath + "00_groupedlist_top_bg_press.sci",
    img_00_header_process_01: imagesPath + theme + "00_header_process_01.png",
    img_00_header_process_02: imagesPath + theme + "00_header_process_02.png",
    img_00_header_process_03: imagesPath + theme + "00_header_process_03.png",
    img_00_header_process_04: imagesPath + theme + "00_header_process_04.png",
    img_00_header_process_05: imagesPath + theme + "00_header_process_05.png",
    img_00_header_process_06: imagesPath + theme + "00_header_process_06.png",
    img_00_header_process_07: imagesPath + theme + "00_header_process_07.png",
    img_00_header_process_08: imagesPath + theme + "00_header_process_08.png",
    img_00_header_process_09: imagesPath + theme + "00_header_process_09.png",
    img_00_header_process_10: imagesPath + theme + "00_header_process_10.png",
    img_00_header_process_11: imagesPath + theme + "00_header_process_11.png",
    img_00_header_process_12: imagesPath + theme + "00_header_process_12.png",
    img_00_header_process_13: imagesPath + theme + "00_header_process_13.png",
    img_00_header_process_14: imagesPath + theme + "00_header_process_14.png",
    img_00_header_process_15: imagesPath + theme + "00_header_process_15.png",
    img_00_header_process_16: imagesPath + theme + "00_header_process_16.png",
    img_00_header_process_17: imagesPath + theme + "00_header_process_17.png",
    img_00_header_process_18: imagesPath + theme + "00_header_process_18.png",
    img_00_header_process_19: imagesPath + theme + "00_header_process_19.png",
    img_00_header_process_20: imagesPath + theme + "00_header_process_20.png",
    img_00_header_process_21: imagesPath + theme + "00_header_process_21.png",
    img_00_header_process_22: imagesPath + theme + "00_header_process_22.png",
    img_00_header_process_23: imagesPath + theme + "00_header_process_23.png",
    img_00_header_process_24: imagesPath + theme + "00_header_process_24.png",
    img_00_header_process_25: imagesPath + theme + "00_header_process_25.png",
    img_00_header_process_26: imagesPath + theme + "00_header_process_26.png",
    img_00_header_process_27: imagesPath + theme + "00_header_process_27.png",
    img_00_header_process_28: imagesPath + theme + "00_header_process_28.png",
    img_00_header_process_29: imagesPath + theme + "00_header_process_29.png",
    img_00_header_process_30: imagesPath + theme + "00_header_process_30.png",
    img_00_icon_Back: imagesPath + "00_icon_Back.png",
    img_00_icon_Back_ef: imagesPath + theme + "00_icon_Back_ef.png",
    img_00_icon_Back_ef_02: imagesPath + theme + "00_icon_Back_ef_02.png",
    img_00_icon_Back_trans_ef: imagesPath + theme + "00_icon_Back_trans_ef.png",
    img_00_icon_jump: imagesPath + "00_icon_jump.png",
    img_00_icon_jump_ef: imagesPath + theme + "00_icon_jump_ef.png",
    img_00_icon_jump_left: imagesPath + "00_icon_jump_left.png",
    img_00_icon_jump_left_ef: imagesPath + theme + "00_icon_jump_left_ef.png",
    img_00_icon_more: imagesPath + "00_icon_more.png",
    img_00_icon_more_ef: imagesPath + theme + "00_icon_more_ef.png",
    img_00_icon_SIP_close: imagesPath + "00_icon_SIP_close.png",
    img_00_icon_SIP_close_ef: imagesPath + theme + "00_icon_SIP_close_ef.png",
    img_00_indexlist_bg: imagesPath + "00_indexlist_bg.sci",
    img_00_indexlist_bg_ef: imagesPath + theme + "00_indexlist_bg_ef.sci",
    img_00_list_group_bg: imagesPath + "00_list_group_bg.sci",
    img_00_list_group_bg_bottom: imagesPath + "00_list_group_bg_bottom.sci",
    img_00_list_group_bg_bottom_ef: imagesPath + theme + "00_list_group_bg_bottom_ef.sci",
    img_00_list_group_bg_bottom_focus: imagesPath + "00_list_group_bg_bottom_focus.sci",
    img_00_list_group_bg_center: imagesPath + "00_list_group_bg_center.sci",
    img_00_list_group_bg_center_ef: imagesPath + theme + "00_list_group_bg_center_ef.sci",
    img_00_list_group_bg_center_focus: imagesPath + "00_list_group_bg_center_focus.sci",
    img_00_list_group_bg_ef: imagesPath + theme + "00_list_group_bg_ef.sci",
    img_00_list_group_bg_focus: imagesPath + "00_list_group_bg_focus.sci",
    img_00_list_group_bg_top: imagesPath + "00_list_group_bg_top.sci",
    img_00_list_group_bg_top_ef: imagesPath + theme + "00_list_group_bg_top_ef.sci",
    img_00_list_group_bg_top_focus: imagesPath + "00_list_group_bg_top_focus.sci",
    img_00_list_group_bottom_cover_round_bg_normal: imagesPath + "00_list_group_bottom_cover_round_bg_normal.sci",
    img_00_list_group_center_cover_round_bg_normal: imagesPath + "00_list_group_center_cover_round_bg_normal.sci",
    img_00_list_group_press_bg: imagesPath + "00_list_group_press_bg.sci",
    img_00_list_group_press_bg_bottom: imagesPath + "00_list_group_press_bg_bottom.sci",
    img_00_list_group_press_bg_center: imagesPath + "00_list_group_press_bg_center.sci",
    img_00_list_group_press_bg_top: imagesPath + "00_list_group_press_bg_top.sci",
    img_00_list_group_single_cover_round_bg_normal: imagesPath + "00_list_group_single_cover_round_bg_normal.sci",
    img_00_list_group_top_cover_round_bg_normal: imagesPath + "00_list_group_top_cover_round_bg_normal.sci",
    img_00_list_process_01: imagesPath + theme + "00_list_process_01.png",
    img_00_list_process_02: imagesPath + theme + "00_list_process_02.png",
    img_00_list_process_03: imagesPath + theme + "00_list_process_03.png",
    img_00_list_process_04: imagesPath + theme + "00_list_process_04.png",
    img_00_list_process_05: imagesPath + theme + "00_list_process_05.png",
    img_00_list_process_06: imagesPath + theme + "00_list_process_06.png",
    img_00_list_process_07: imagesPath + theme + "00_list_process_07.png",
    img_00_list_process_08: imagesPath + theme + "00_list_process_08.png",
    img_00_list_process_09: imagesPath + theme + "00_list_process_09.png",
    img_00_list_process_10: imagesPath + theme + "00_list_process_10.png",
    img_00_list_process_11: imagesPath + theme + "00_list_process_11.png",
    img_00_list_process_12: imagesPath + theme + "00_list_process_12.png",
    img_00_list_process_13: imagesPath + theme + "00_list_process_13.png",
    img_00_list_process_14: imagesPath + theme + "00_list_process_14.png",
    img_00_list_process_15: imagesPath + theme + "00_list_process_15.png",
    img_00_list_process_16: imagesPath + theme + "00_list_process_16.png",
    img_00_list_process_17: imagesPath + theme + "00_list_process_17.png",
    img_00_list_process_18: imagesPath + theme + "00_list_process_18.png",
    img_00_list_process_19: imagesPath + theme + "00_list_process_19.png",
    img_00_list_process_20: imagesPath + theme + "00_list_process_20.png",
    img_00_list_process_21: imagesPath + theme + "00_list_process_21.png",
    img_00_list_process_22: imagesPath + theme + "00_list_process_22.png",
    img_00_list_process_23: imagesPath + theme + "00_list_process_23.png",
    img_00_list_process_24: imagesPath + theme + "00_list_process_24.png",
    img_00_list_process_25: imagesPath + theme + "00_list_process_25.png",
    img_00_list_process_26: imagesPath + theme + "00_list_process_26.png",
    img_00_list_process_27: imagesPath + theme + "00_list_process_27.png",
    img_00_list_process_28: imagesPath + theme + "00_list_process_28.png",
    img_00_list_process_29: imagesPath + theme + "00_list_process_29.png",
    img_00_list_process_30: imagesPath + theme + "00_list_process_30.png",
    img_00_more_popup_press: imagesPath + theme + "00_more_popup_press.sci",
    img_00_option_panel_contextual_popup_arrow: imagesPath + "00_option_panel_contextual_popup_arrow.png",
    img_00_option_panel_handle_bg: imagesPath + "00_option_panel_handle_bg.png",
    img_00_option_panel_handle_bg_ef: imagesPath + theme + "00_option_panel_handle_bg_ef.png",
    img_00_option_panel_handle_bg_ef_press: imagesPath + theme + "00_option_panel_handle_bg_ef_press.png",
    img_00_option_panel_handle_bg_press: imagesPath + "00_option_panel_handle_bg_press.png",
    img_00_option_panel_handle_more: imagesPath + "00_option_panel_handle_more.png",
    img_00_option_panel_handle_more_press: imagesPath + "00_option_panel_handle_more_press.png",
    img_00_overscrolling_bottom: imagesPath + theme + "00_overscrolling_bottom.sci",
    img_00_overscrolling_left: imagesPath + theme + "00_overscrolling_left.sci",
    img_00_overscrolling_right: imagesPath + theme + "00_overscrolling_right.sci",
    img_00_overscrolling_top: imagesPath + theme + "00_overscrolling_top.sci",
    img_00_panel_bg: imagesPath + "00_panel_bg.sci",
    img_00_panel_handle_arrow: imagesPath + "00_panel_handle_arrow.png",
    img_00_panel_handle_bg: imagesPath + "00_panel_handle_bg.sci",
    img_00_panel_handle_bg_ef: imagesPath + theme + "00_panel_handle_bg_ef.sci",
    img_00_panel_handle_bg_ef_press: imagesPath + theme + "00_panel_handle_bg_ef_press.sci",
    img_00_panel_list_bg_ef_press: imagesPath + theme + "00_panel_list_bg_ef_press.sci",
    img_00_panel_list_bg_press: imagesPath + "00_panel_list_bg_press.sci",
    img_00_picker_button: imagesPath + "00_picker_button.sci",
    img_00_picker_button_dim_ef: imagesPath + theme + "00_picker_button_dim_ef.sci",
    img_00_picker_button_ef: imagesPath + theme + "00_picker_button_ef.sci",
    img_00_picker_button_focus: imagesPath + "00_picker_button_focus.sci",
    img_00_picker_button_press_ef: imagesPath + theme + "00_picker_button_press_ef.sci",
    img_00_popup_bg: imagesPath + theme + "00_popup_bg.sci",
    img_00_popup_bg_ef: imagesPath + theme + "00_popup_bg_ef.sci",
    img_00_popup_bubble_bg: imagesPath + theme + "00_popup_bubble_bg.sci",
    img_00_popup_bubble_bg_ef: imagesPath + theme + "00_popup_bubble_bg_ef.sci",
    img_00_popup_bubble_tail_bottom: imagesPath + theme + "00_popup_bubble_tail_bottom.png",
    img_00_popup_bubble_tail_bottom_ef: imagesPath + theme + "00_popup_bubble_tail_bottom_ef.png",
    img_00_popup_bubble_tail_left: imagesPath + theme + "00_popup_bubble_tail_left.png",
    img_00_popup_bubble_tail_left_ef: imagesPath + theme + "00_popup_bubble_tail_left_ef.png",
    img_00_popup_bubble_tail_right: imagesPath + theme + "00_popup_bubble_tail_right.png",
    img_00_popup_bubble_tail_right_ef: imagesPath + theme + "00_popup_bubble_tail_right_ef.png",
    img_00_popup_bubble_tail_top: imagesPath + theme + "00_popup_bubble_tail_top.png",
    img_00_popup_bubble_tail_top_ef: imagesPath + theme + "00_popup_bubble_tail_top_ef.png",
    img_00_popup_button_bg_ef: imagesPath + theme + "00_popup_button_bg_ef.sci",
    img_00_popup_dim_lighting: imagesPath + theme + "00_popup_dim_lighting.png",
    img_00_popup_dim_lighting_h: imagesPath + theme + "00_popup_dim_lighting_h.png",
    img_00_popup_title_bg: imagesPath + "00_popup_title_bg.png",
    img_00_popup_title_bg_ef: imagesPath + "00_popup_title_bg_ef.png",
    img_00_progress_bar: imagesPath + "00_progress_bar.sci",
    img_00_progress_bar_ef: imagesPath + theme + "00_progress_bar_ef.sci",
    img_00_progress_bg: imagesPath + "00_progress_bg.sci",
    img_00_progress_ef_bg: imagesPath + theme + "00_progress_ef_bg.sci",
    img_00_scroll_bar_h: imagesPath + "00_scroll_bar_h.sci",
    img_00_scroll_bar_handler_h: imagesPath + theme + "00_scroll_bar_handler_h.png",
    img_00_scroll_bar_handler_v: imagesPath + theme + "00_scroll_bar_handler_v.png",
    img_00_scroll_bar_h_ef: imagesPath + "00_scroll_bar_h_ef.sci",
    img_00_scroll_bar_v: imagesPath + "00_scroll_bar_v.sci",
    img_00_scroll_bar_v_ef: imagesPath + "00_scroll_bar_v_ef.sci",
    img_00_search_edit_field_bg: imagesPath + "00_search_edit_field_bg.sci",
    img_00_search_edit_field_bg_ef: imagesPath + theme + "00_search_edit_field_bg_ef.sci",
    img_00_search_icon: imagesPath + "00_search_icon.png",
    img_00_search_icon_ef: imagesPath + theme + "00_search_icon_ef.png",
    img_00_slider_bg: imagesPath + theme + "00_slider_bg.sci",
    img_00_slider_handle: imagesPath + "00_slider_handle.png",
    img_00_slider_handle_ef: imagesPath + theme + "00_slider_handle_ef.png",
    img_00_slider_handle_ef_dim: imagesPath + theme + "00_slider_handle_ef_dim.png",
    img_00_slider_handle_ef_press: imagesPath + theme + "00_slider_handle_ef_press.png",
    img_00_slider_handle_focus: imagesPath + "00_slider_handle_focus.png",
    img_00_slider_popup_bg: imagesPath + "00_slider_popup_bg.sci",
    img_00_slider_popup_bg_ef: imagesPath + theme + "00_slider_popup_bg_ef.sci",
    img_00_softkey_icon_add: imagesPath + "00_softkey_icon_add.png",
    img_00_softkey_icon_zoom: imagesPath + "00_softkey_icon_zoom.png",
    img_00_softkey_left_bg: imagesPath + "00_softkey_left_bg.png",
    img_00_softkey_left_bg_ef: imagesPath + theme + "00_softkey_left_bg_ef.png",
    img_00_softkey_left_bg_ef_press: imagesPath + theme + "00_softkey_left_bg_ef_press.png",
    img_00_softkey_left_text_bg: imagesPath + "00_softkey_left_text_bg.png",
    img_00_softkey_left_text_bg_ef: imagesPath + theme + "00_softkey_left_text_bg_ef.png",
    img_00_softkey_left_text_bg_ef_press: imagesPath + theme + "00_softkey_left_text_bg_ef_press.png",
    img_00_softkey_right_bg: imagesPath + "00_softkey_right_bg.png",
    img_00_softkey_right_bg_ef: imagesPath + theme + "00_softkey_right_bg_ef.png",
    img_00_softkey_right_bg_ef_press: imagesPath + theme + "00_softkey_right_bg_ef_press.png",
    img_00_softkey_right_text_bg: imagesPath + "00_softkey_right_text_bg.png",
    img_00_softkey_right_text_bg_ef: imagesPath + theme + "00_softkey_right_text_bg_ef.png",
    img_00_softkey_right_text_bg_ef_press: imagesPath + theme + "00_softkey_right_text_bg_ef_press.png",
    img_00_split_handler_bg: imagesPath + "00_split_handler_bg.sci",
    img_00_split_handler_bg_ef_h: imagesPath + theme + "00_split_handler_bg_ef_h.sci",
    img_00_split_handler_bg_ef_v: imagesPath + theme + "00_split_handler_bg_ef_v.sci",
    img_00_split_handler_h: imagesPath + theme + "00_split_handler_h.png",
    img_00_split_handler_v: imagesPath + theme + "00_split_handler_v.png",
    img_00_system_control_bg: imagesPath + "00_system_control_bg.sci",
    img_00_tab_bg: imagesPath + "00_tab_bg.sci",
    img_00_tab_bg_focus_ef: imagesPath + "00_tab_bg_focus_ef.png",
    img_00_tab_bg_line_ef: imagesPath + "00_tab_bg_line_ef.png",
    img_00_tab_focus: imagesPath + "00_tab_focus.sci",
    img_00_tab_press_ef: imagesPath + "00_tab_press_ef.sci",
    img_00_thumbs_bg_focus: imagesPath + "00_thumbs_bg_focus.sci",
    img_00_thumbs_line_bg: imagesPath + "00_thumbs_line_bg.sci",
    img_00_time_picker_keypad_bg: imagesPath + "00_time_picker_keypad_bg.sci",
    img_00_time_picker_keypad_button_bg: imagesPath + "00_time_picker_keypad_button_bg.sci",
    img_00_time_picker_keypad_button_bg_ef: imagesPath + "00_time_picker_keypad_button_bg_ef.sci",
    img_00_time_picker_number_bg: imagesPath + "00_time_picker_number_bg.sci",
    img_00_time_picker_tail: imagesPath + "00_time_picker_tail.png",
    img_00_time_picker_tail_01: imagesPath + "00_time_picker_tail_01.png",
    img_00_title_bg: imagesPath + "00_title_bg.sci",
    img_00_title_bg_ef: imagesPath + "00_title_bg_ef.png",
    img_00_toolbar_bg: imagesPath + "00_toolbar_bg.sci",
    img_00_toolbar_bg_ef: imagesPath + theme + "00_toolbar_bg_ef.sci",
    img_00_toolbar_bg_shadow: imagesPath + theme + "00_toolbar_bg_shadow.sci",
    img_00_toolbar_button: imagesPath + theme + "00_toolbar_button.sci",
    img_00_toolbar_button_bg: imagesPath + "00_toolbar_button_bg.sci",
    img_00_toolbar_button_ef: imagesPath + theme + "00_toolbar_button_ef.sci",
    img_00_toolbar_button_ef_focus: imagesPath + "00_toolbar_button_ef_focus.sci",
    img_00_toolbar_button_ef_press: imagesPath + theme + "00_toolbar_button_ef_press.sci",
    img_00_toolbar_button_press: imagesPath + theme + "00_toolbar_button_press.sci",
    img_00_toolbar_ef_press: imagesPath + theme + "00_toolbar_ef_press.sci",
    img_00_toolbar_press: imagesPath + "00_toolbar_press.sci",
    img_copy_and_paste_Handler_center: imagesPath + "copy_and_paste_Handler_center.png",
    img_copy_and_paste_Handler_center_reverse: imagesPath + "copy_and_paste_Handler_center_reverse.png",
    img_copy_and_paste_Handler_left: imagesPath + "copy_and_paste_Handler_left.png",
    img_copy_and_paste_Handler_left_01: imagesPath + "copy_and_paste_Handler_left_01.png",
    img_copy_and_paste_Handler_left_reverse: imagesPath + "copy_and_paste_Handler_left_reverse.png",
    img_copy_and_paste_Handler_right: imagesPath + "copy_and_paste_Handler_right.png",
    img_copy_and_paste_icon_search: imagesPath + "copy_and_paste_icon_search.png",
    img_copy_and_paste_Magnifier: imagesPath + "copy_and_paste_Magnifier.sci",
    img_pd_btn_bg: imagesPath + theme + "pd_btn_bg.sci",
    img_pd_btn_bg_arrow_down: imagesPath + theme + "pd_btn_bg_arrow_down.png",
    img_pd_btn_bg_arrow_up: imagesPath + theme + "pd_btn_bg_arrow_up.png",
    img_TTS_focus: imagesPath + "TTS_focus.sci",
    img_TTS_popup_bg: imagesPath + "TTS_popup_bg.sci",
}
